name: invoke-workflow
on:
  workflow_dispatch:
     inputs:
      image:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'frinx/schellar:latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test
        env:
          IMAGE: ${{ inputs.image }}
        run: |
          curl -L -X POST https://api.github.com/repos/Jozefiel/monorepo-api/actions/workflows/release-discovery.yml/dispatches \
          -u "Jozefiel:${{ secrets.GITHUB_TOKEN }}"
          -H 'Accept: application/vnd.github+json' \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --data '{"ref":"master","inputs":{"image":"IMAGE"}}'
